# Generated by Django 4.1 on 2022-08-25 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0003_transaction_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receipt',
        ),
        migrations.AddField(
            model_name='receipt',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.transaction'),
        ),
    ]
