# Generated by Django 4.1 on 2022-08-25 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='Customer_id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='thirdparty',
            old_name='Phone_number',
            new_name='phone_number',
        ),
    ]
